# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
stage: deploy
script:
- mkdir public
- cp -r ./webpage/* ./public
- cp -r ./css ./public
- cp -r ./img ./public
- cp -r ./script ./public

artifacts:
rules:
if: $CI COMMIT BRANCH == $CI DEFAULT BRANCH
paths :
- public

